# --- ETAPA 1: Compilación ---
FROM maven:3.9.6-eclipse-temurin-17-alpine AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn package -DskipTests

# --- ETAPA 2: Entorno de Producción ---
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

COPY --from=build /app/target/*.jar app.jar

# Puerto diferenciado para el microservicio de Ventas
EXPOSE 8082

ENTRYPOINT ["java", "-jar", "app.jar"]